readthedocs/bookmarks/urls.py
from django.conf.urls.defaults import patterns, url


urlpatterns = patterns(
    # base view, flake8 complains if it is on the previous line.
    'bookmarks.views',
    url(r'^$',
        'bookmark_list',
        name='bookmarks_list'),

    url(r'^add/(?P<url>.*)/$',
        'bookmark_add',
        name='bookmarks_add'),

    url(r'^remove/(?P<url>.*)/$',
        'bookmark_remove',
        name='bookmarks_remove'),
)

readthedocs/builds/urls.py
from django.conf.urls.defaults import patterns, url


urlpatterns = patterns(
    # base view, flake8 complains if it is on the previous line.
    'builds.views',
    url(r'^$',
        'build_list',
        name='builds_list'),

    url(r'^(?P<project_slug>[-\w]+)/(?P<pk>\d+)/$',
        'build_detail',
        name='builds_detail'),

    url(r'^(?P<project_slug>[-\w]+)/$',
        'build_list',
        name='builds_project_list'),

    url(r'^tag/(?P<tag>\w+)/$',
        'build_list',
        name='builds_tag_list'),
)

readthedocs/restapi/urls.py
from django.conf.urls.defaults import url, patterns, include

from rest_framework import routers

from .views.model_views import ProjectViewSet, NotificationViewSet, VersionViewSet

router = routers.DefaultRouter()
router.register(r'version', VersionViewSet)
router.register(r'project', ProjectViewSet)
router.register(r'notification', NotificationViewSet)

urlpatterns = patterns(
    '',
	url(r'^', include(router.urls)),
    url(r'footer_html/', 'restapi.views.footer_views.footer_html', name='footer_html'),
    url(r'quick_search/', 'restapi.views.search_views.quick_search', name='quick_search'),
    url(r'index_search/', 'restapi.views.search_views.index_search', name='index_search'),
    url(r'search/$', 'restapi.views.search_views.search', name='search'),
    url(r'search/project/$', 'restapi.views.search_views.project_search', name='project_search'),
    url(r'search/section/$', 'restapi.views.search_views.section_search', name='section_search'),
)

readthedocs/urls.py
from django.conf.urls.defaults import url, patterns, include
from django.contrib import admin
from django.conf import settings
from django.views.generic.simple import direct_to_template

from tastypie.api import Api

from api.base import (ProjectResource, UserResource, BuildResource,
                      VersionResource, FileResource)
from builds.filters import VersionFilter
from core.forms import UserProfileForm
from core.views import SearchView
from projects.feeds import LatestProjectsFeed, NewProjectsFeed
from projects.filters import ProjectFilter
from projects.constants import LANGUAGES_REGEX

v1_api = Api(api_name='v1')
v1_api.register(BuildResource())
v1_api.register(UserResource())
v1_api.register(ProjectResource())
v1_api.register(VersionResource())
v1_api.register(FileResource())

admin.autodiscover()

handler500 = 'core.views.server_error'
handler404 = 'core.views.server_error_404'

urlpatterns = patterns(
    '',  # base view, flake8 complains if it is on the previous line.
    url(r'^$', 'core.views.homepage'),
    url(r'^security/', direct_to_template, {'template': 'security.html'}),

    # For serving docs locally and when nginx isn't
    url((r'^docs/(?P<project_slug>[-\w]+)/(?P<lang_slug>%s)/(?P<version_slug>'
         r'[-._\w]+?)/(?P<filename>.*)$') % LANGUAGES_REGEX,
        'core.views.serve_docs',
        name='docs_detail'),

    # Redirect to default version, if only lang_slug is set.
    url((r'^docs/(?P<project_slug>[-\w]+)/(?P<lang_slug>%s)/$') % LANGUAGES_REGEX,
        'core.views.redirect_lang_slug',
        name='docs_detail'),

    # Redirect to default version, if only version_slug is set.
    url(r'^docs/(?P<project_slug>[-\w]+)/(?P<version_slug>[-._\w]+)/$',
        'core.views.redirect_version_slug',
        name='docs_detail'),

    # Redirect to default version.
    url(r'^docs/(?P<project_slug>[-\w]+)/$',
        'core.views.redirect_project_slug',
        name='docs_detail'),

    # Handle /page/<path> redirects for explicit "latest" version goodness.
    url(r'^docs/(?P<project_slug>[-\w]+)/page/(?P<filename>.*)$',
        'core.views.redirect_page_with_filename',
        name='docs_detail'),

    # Handle single version URLs
    url(r'^docs/(?P<project_slug>[-\w]+)/(?P<filename>.*)$',
        'core.views.serve_single_version_docs',
        name='docs_detail'),

    # Handle fallbacks
    url(r'^user_builds/(?P<project_slug>[-\w]+)/rtd-builds/(?P<version_slug>[-._\w]+?)/(?P<filename>.*)$',
        'core.views.server_helpful_404',
        name='user_buils_fallback'),
    url(r'^user_builds/(?P<project_slug>[-\w]+)/translations/(?P<lang_slug>%s)/(?P<version_slug>[-._\w]+?)/(?P<filename>.*)$' % LANGUAGES_REGEX,
        'core.views.server_helpful_404',
        name='user_builds_fallback_translations'),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^projects/', include('projects.urls.public')),
    url(r'^builds/', include('builds.urls')),
    url(r'^flagging/', include('basic.flagging.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^search/project/', SearchView.as_view(), name='haystack_project'),
    url(r'^search/', include('haystack.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dashboard/', include('projects.urls.private')),
    url(r'^github', 'core.views.github_build', name='github_build'),
    url(r'^bitbucket', 'core.views.bitbucket_build', name='bitbucket_build'),
    url(r'^build/(?P<pk>[-\w]+)',
        'core.views.generic_build',
        name='generic_build'),
    url(r'^random/(?P<project>[\w-]+)',
        'core.views.random_page',
        name='random_page'),
    url(r'^random/$', 'core.views.random_page', name='random_page'),
    url(r'^depth/$', 'core.views.queue_depth', name='queue_depth'),
    url(r'^queue_info/$', 'core.views.queue_info', name='queue_info'),
    url(r'^live/$', 'core.views.live_builds', name='live_builds'),
    url(r'^500/$', 'core.views.divide_by_zero', name='divide_by_zero'),
    url(r'^filter/version/$',
        'django_filters.views.object_filter',
        {'filter_class': VersionFilter, 'template_name': 'filter.html'},
        name='filter_version'),
    url(r'^filter/project/$',
        'django_filters.views.object_filter',
        {'filter_class': ProjectFilter, 'template_name': 'filter.html'},
        name='filter_project'),
    url(r'^wipe/(?P<project_slug>[-\w]+)/(?P<version_slug>[\w]{1}[-\w\.]+)/$',
        'core.views.wipe_version',
        name='wipe_version'),
    url(r'^profiles/create/', 'profiles.views.create_profile',
        {'form_class': UserProfileForm},
        name='profiles_profile_create'),
    url(r'^profiles/edit/', 'profiles.views.edit_profile',
        {'form_class': UserProfileForm},
        name='profiles_profile_edit'),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^api/', include(v1_api.urls)),
    url(r'^api/v2/', include('restapi.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^feeds/new/$',
        NewProjectsFeed(),
        name="new_feed"),
    url(r'^feeds/latest/$',
        LatestProjectsFeed(),
        name="latest_feed"),
    url(r'^mlt/(?P<project_slug>[-\w]+)/(?P<filename>.*)$',
        'core.views.morelikethis',
        name='morelikethis'),
    url(r'^websupport/', include('websupport.urls')),

)

if settings.DEBUG:
    urlpatterns += patterns(
        '',  # base view, flake8 complains if it is on the previous line.
        url('style-catalog/$',
            'django.views.generic.simple.direct_to_template',
            {'template': 'style_catalog.html'}),
        url(regex='^%s/(?P<path>.*)$' % settings.MEDIA_URL.strip('/'),
            view='django.views.static.serve',
            kwargs={'document_root': settings.MEDIA_ROOT}),
    )

readthedocs/projects/models.py
import fnmatch
import logging
import os
from urlparse import urlparse

from distlib.version import UnsupportedVersionError
from django.conf import settings
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _

from guardian.shortcuts import assign, get_objects_for_user

from betterversion.better import version_windows, BetterVersion
from projects import constants
from projects.exceptions import ProjectImportError
from projects.templatetags.projects_tags import sort_version_aware
from projects.utils import (highest_version as _highest, make_api_version,
                            symlink, update_static_metadata)
from taggit.managers import TaggableManager
from tastyapi.slum import api

from vcs_support.base import VCSProject
from vcs_support.backends import backend_cls
from vcs_support.utils import Lock, NonBlockingLock


log = logging.getLogger(__name__)


class ProjectManager(models.Manager):
    def _filter_queryset(self, user, privacy_level):
        if isinstance(privacy_level, basestring):
            privacy_level = (privacy_level,)
        queryset = Project.objects.filter(privacy_level__in=privacy_level)
        if not user:
            return queryset
        else:
            # Hack around get_objects_for_user not supporting global perms
            global_access = user.has_perm('projects.view_project')
            if global_access:
                queryset = Project.objects.all()
        if user.is_authenticated():
            # Add in possible user-specific views
            user_queryset = get_objects_for_user(user, 'projects.view_project')
            queryset = user_queryset | queryset
        return queryset.filter()

    def live(self, *args, **kwargs):
        base_qs = self.filter(skip=False)
        return base_qs.filter(*args, **kwargs)

    def public(self, user=None, *args, **kwargs):
        """
        Query for projects, privacy_level == public
        """
        queryset = self._filter_queryset(user, privacy_level=constants.PUBLIC)
        return queryset.filter(*args, **kwargs)

    def protected(self, user=None, *args, **kwargs):
        """
        Query for projects, privacy_level != private
        """
        queryset = self._filter_queryset(user,
                                         privacy_level=(constants.PUBLIC,
                                                        constants.PROTECTED))
        return queryset.filter(*args, **kwargs)

    def private(self, user=None, *args, **kwargs):
        """
        Query for projects, privacy_level != private
        """
        queryset = self._filter_queryset(user, privacy_level=constants.PRIVATE)
        return queryset.filter(*args, **kwargs)


class ProjectRelationship(models.Model):
    parent = models.ForeignKey('Project', verbose_name=_('Parent'),
                               related_name='subprojects')
    child = models.ForeignKey('Project', verbose_name=_('Child'),
                              related_name='superprojects')

    def __unicode__(self):
        return "%s -> %s" % (self.parent, self.child)

    #HACK
    def get_absolute_url(self):
        return ("http://%s.readthedocs.org/projects/%s/%s/latest/"
                % (self.parent.slug, self.child.slug, self.child.language))


class Project(models.Model):
    #Auto fields
    pub_date = models.DateTimeField(_('Publication date'), auto_now_add=True)
    modified_date = models.DateTimeField(_('Modified date'), auto_now=True)

    #Generally from conf.py
    users = models.ManyToManyField(User, verbose_name=_('User'),
                                   related_name='projects')
    name = models.CharField(_('Name'), max_length=255)
    slug = models.SlugField(_('Slug'), max_length=255, unique=True)
    description = models.TextField(_('Description'), blank=True,
                                   help_text=_('The reStructuredText '
                                               'description of the project'))
    repo = models.CharField(_('Repository URL'), max_length=100, blank=True,
                            help_text=_('Checkout URL for your code (hg, git, '
                                        'etc.). Ex. http://github.com/'
                                        'ericholscher/django-kong.git'))
    repo_type = models.CharField(_('Repository type'), max_length=10,
                                 choices=constants.REPO_CHOICES, default='git')
    project_url = models.URLField(_('Project URL'), blank=True,
                                  help_text=_('The project\'s homepage'),
                                  verify_exists=False)
    canonical_url = models.URLField(_('Canonical URL'), blank=True,
                                  help_text=_('The official URL that the docs live at. This can be at readthedocs.org, or somewhere else. Ex. http://docs.fabfile.org'),
                                  verify_exists=False)
    version = models.CharField(_('Version'), max_length=100, blank=True,
                               help_text=_('Project version these docs apply '
                                           'to, i.e. 1.0a'))
    copyright = models.CharField(_('Copyright'), max_length=255, blank=True,
                                 help_text=_('Project copyright information'))
    theme = models.CharField(
        _('Theme'), max_length=20, choices=constants.DEFAULT_THEME_CHOICES,
        default=constants.THEME_DEFAULT,
        help_text=(u'<a href="http://sphinx.pocoo.org/theming.html#builtin-'
                   'themes" target="_blank">%s</a>') % _('Examples'))
    suffix = models.CharField(_('Suffix'), max_length=10, editable=False,
                              default='.rst')
    single_version = models.BooleanField(
        _('Single version'), default=False,
        help_text=_('A single version site has no translations and only your "latest" version, served at the root of the domain. Use this with caution, only turn it on if you will <b>never</b> have multiple versions of your docs.'))
    default_version = models.CharField(
        _('Default version'), max_length=255, default='latest',
        help_text=_('The version of your project that / redirects to'))
    # In default_branch, None max_lengtheans the backend should choose the
    # appropraite branch. Eg 'master' for git
    default_branch = models.CharField(
        _('Default branch'), max_length=255, default=None, null=True,
        blank=True, help_text=_('What branch "latest" points to. Leave empty '
                                'to use the default value for your VCS (eg. '
                                'trunk or master).'))
    requirements_file = models.CharField(
        _('Requirements file'), max_length=255, default=None, null=True,
        blank=True, help_text=_(
            'Requires Virtualenv. A <a '
            'href="http://www.pip-installer.org/en/latest/cookbook.html#requirements-files">'
            'pip requirements file</a> needed to build your documentation. '
            'Path from the root of your project.'))
    documentation_type = models.CharField(
        _('Documentation type'), max_length=20,
        choices=constants.DOCUMENTATION_CHOICES, default='sphinx',
        help_text=_('Type of documentation you are building. <a href="http://'
                    'sphinx-doc.org/builders.html#sphinx.builders.html.'
                    'DirectoryHTMLBuilder">More info</a>.'))
    analytics_code = models.CharField(
        _('Analytics code'), max_length=50, null=True, blank=True,
        help_text=_("Google Analytics Tracking ID (ex. UA-22345342-1). "
                    "This may slow down your page loads."))

    # Other model data.
    path = models.CharField(_('Path'), max_length=255, editable=False,
                            help_text=_("The directory where conf.py lives"))
    conf_py_file = models.CharField(
        _('Python configuration file'), max_length=255, default='', blank=True,
        help_text=_('Path from project root to conf.py file (ex. docs/conf.py)'
                    '. Leave blank if you want us to find it for you.'))

    featured = models.BooleanField(_('Featured'))
    skip = models.BooleanField(_('Skip'))
    mirror = models.BooleanField(_('Mirror'), default=False)
    use_virtualenv = models.BooleanField(
        _('Use virtualenv'),
        help_text=_("Install your project inside a virtualenv using setup.py "
                    "install"))

    # This model attribute holds the python interpreter used to create the
    # virtual environment
    python_interpreter = models.CharField(
        _('Python Interpreter'),
        max_length=20,
        choices=constants.PYTHON_CHOICES,
        default='python',
        help_text=_("(Beta) The Python interpreter used to create the virtual "
                    "environment."))

    use_system_packages = models.BooleanField(
        _('Use system packages'),
        help_text=_("Give the virtual environment access to the global "
                    "site-packages dir."))
    django_packages_url = models.CharField(_('Django Packages URL'),
                                           max_length=255, blank=True)
    privacy_level = models.CharField(
        _('Privacy Level'), max_length=20, choices=constants.PRIVACY_CHOICES,
        default='public',
        help_text=_("(Beta) Level of privacy that you want on the repository. "
                    "Protected means public but not in listings."))
    version_privacy_level = models.CharField(
        _('Version Privacy Level'), max_length=20,
        choices=constants.PRIVACY_CHOICES, default='public',
        help_text=_("(Beta) Default level of privacy you want on built "
                    "versions of documentation."))

    # Subprojects
    related_projects = models.ManyToManyField(

readthedocs/templates/builds/build_detail.html
{% extends "projects/base_project.html" %}

{% load i18n %}

{% block title %}{{ build.project.name }}{% endblock %}


{% block project_editing %}
    {% with builds_active="active" %}
        {% include "core/project_bar.html" %}
    {% endwith %}
{% endblock %}

{% block content-header %}<h1>{% blocktrans with build.project.name as project_name %}Build for {{ project_name }}{% endblocktrans %}</h1>{% endblock %}

{% block content %}
  <div id="build-{{ build.id }}">
    <p>{% blocktrans with build.date|date:"N j, Y. P" as build_date %}Built: {{ build_date }}{% endblocktrans %}</p>

    <p>{% trans "State:" %} <b><span id="build-state">{{ build.get_state_display }}</span></b>
      <img src="{{ MEDIA_URL }}images/loader.gif" class="hide build-loading">
    </p>

    <p>{% trans "Outcome:" %}
      <b>
        <span id="build-success">
          {% if build.state != 'finished' %}{% trans "Not yet finished" %} {% else %} {% if build.success %}{% trans "Passed" %}{% else %}{% trans "Failed" %}{% endif %}{% endif %} {% if not build.success %} ({% trans "Status Code:" %} {{ build.exit_code }}){% endif %}
        </span>
      </b>
    </p>

    {% if build.version %}
    <p>{% trans "Version:" %} <b>{{ build.version.slug }}</b></p>
    {% endif %}

    <p>{% trans "Type:" %} <b>{{ build.type }}</b></p>

    <h3>{% trans "Sphinx Standard Output" %}</h3>
    <pre class="build-output"><span id="build-output">{{ build.output }}</span></pre>

    {% if build.error %}
    <h3>{% trans "Sphinx Standard Error" %}</h3>
    <pre class="build-error"><span id="build-error">{{ build.error }}</span></pre>
    {% endif %}

    {% if build.setup %}
    <h3>{% trans "Setup Output" %}</h3>
    <pre class="build-output"><span id="build-setup">{{ build.setup }}</span></pre>
    {% endif %}

    {% if build.setup_error %}
    <h3>{% trans "Environment Standard Error" %}</h3>
    <pre class="build-error"><span id="build-setup_error">{{ build.setup_error }}</span></pre>
    {% endif %}
  </div>
    <form id="form" style="display: none;">
        <input type="submit">
    </form>
{% endblock %}

{% block extra_scripts %}
{{ block.super }}
  <script type="text/javascript" src="{{ MEDIA_URL }}javascript/build_updater.js"></script>

  <script type="text/javascript">
    $(function() {
        new BuildUpdater({{ build.id }}).startPolling();
    });

    $(function() {
        var WS = false;
        if (window.WebSocket) WS = WebSocket;
        if (!WS && window.MozWebSocket) WS = MozWebSocket;
        if (!WS)
            alert('Your browser does not seem to support Websockets.');

        var $results = $('#results');
        var $form = $('#form');
        var $url = $('#url');
        var $status = $('#status');
        var $build_output = $('#build-output');

        var ws = new WS('ws://localhost:8088/websocket');
        ws.send_json = function(data) {
            this.send(JSON.stringify(data));
        }
        ws.onopen = function() {
            console.log('websocket connected');
            $form.submit()
        };
        ws.onmessage = function(message) {
            console.log(message);
            var data = JSON.parse(message.data);
            switch (data.cmd) {
                case 'status':
                    $build_output.append(data.status);
                    window.scrollBy(0,50);
                    break;
                case 'result':
                    console.log(data.result);
                    var result = data.result;
                    var $result = $('<tr/>')
                    $result.append($('<td>' + result.status_code + '</td>'))
                    $result.append($('<td>' + result.url + '</td>'))
                    $result.append($('<td>' + result.length + '</td>'))
                    $result.append($('<td>' + (result.duration*1000) + '</td>'))
                    $results.append($result);
                    break;
            }
        };
        ws.onclose = function() {
            console.log('websocket closed');
        };
        $form.bind('submit', function(e) {
            e.preventDefault();
            //var url = $url.val();
            ws.send_json({cmd: 'tail', url: '/tmp/docs-build-{{ build.id }}'});
            //$form.hide()
            console.log(url);
        });

    });

  </script>
{% endblock %}

readthedocs/templates/builds/build_list.html
{% extends "projects/base_project.html" %}

{% load i18n %}

{% load pagination_tags %}

{% block title %}Builds{% endblock %}

{% block project_editing %}
    {% with builds_active="active" %}
        {% include "core/project_bar.html" %}
    {% endwith %}
{% endblock %}

{% block content %}
<div id="build_list">

        {% comment %}
        <form action="" method="get">
            {{ filter.form.as_p }}
            <input type="submit" value="Filter" />
        </form>
        {% endcomment %}

        {% autopaginate build_list 15 %}

        <!-- BEGIN builds list -->
        <div class="module">
          <div class="module-wrapper">

            <div class="module-header">
              <div style="float:right;">
                <form method="post" action="{% url generic_build project.pk %}">
                  <ul class="build_a_version">
                    <li style="display: inline-block">
                      <input style="display: inline-block" type="submit" value="{% trans "Build Version:" %}">
                    </li>
                    <li style="display: inline-block">
                      <select id="id_version" name="version_slug">
                      {% for version in project.ordered_active_versions %}
                        <option value="{{ version.slug }}">{{ version.slug }}</option>
                      {% endfor %}
                      </select>
                    </li>
                  </form>
                </div>
              </div>
              <h1>{% trans "Recent Builds" %}</h1>
            </div>

            <div class="module-list">
              <div class="module-list-wrapper">
                <ul>
                  {% include "core/build_list_detailed.html" %}
                </ul>
              </div>
            </div>

          </div>
        </div>
        <!-- END builds list -->

        {% paginate %}

</div>

{% endblock %}

{% block extra_scripts %}
{{ block.super }}
  <script type="text/javascript" src="{{ MEDIA_URL }}javascript/build_updater.js"></script>

  <script type="text/javascript">
    $(function() {
      {% for build in active_builds %}
        $('#build-{{ build.id }}').effect('highlight', {}, 3000);
        new BuildListUpdater({{ build.id }}).startPolling();
      {% endfor %}
    });
  </script>
{% endblock %}

readthedocs/templates/builds/tag_list.html
{% extends "projects/base_project.html" %}

{% load i18n %}

{% block title %}{% trans "Popular tags" %}{% endblock %}

{% block content %}
  <ul>
  {% for tag in tag_list %}
    <li><a href="{% url projects_tag_detail tag.slug %}">{{ tag.name }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}